### ISSUE TITLE
Where do the installers come from?

### ISSUE THREAD

**Issue by lextm** [edgardo001/PHPManagerForIIS-Versiones#1]
PHP Manager for IIS is an open source project, so everyone can do whatever he/she likes, but since you are not the original developer, and this repo does not contain any source code, more information should be provided. 

Readers should be warned as it is not clear from where the installers come from. If they were modified by you in any way, you should provide enough information to reveal what was changed.

**Comment by edgardo001** [comment]
Dear, all the reason.
These installers are not my development or package, it is just a compilation of functional packages for IIS in each of the Windows versions (it can be obtained from "Web Platform Installer", but it is installed automatically, the installer is not distributed as a file ).

I started using them in the version "PHPManagerForIIS-1.2.0-x64 - IIS 7.msi" that I downloaded from CodePlex, when I updated to Windows 8 it was very difficult to find the corresponding version, since it does not follow the thread in codeplex, when I updated to Windows 10, I had the same problem to find it, for this reason I loaded these installers in Github, they do not have any modification, they are the originals, if they have a defect or "malware", I do not know. He used them for tests in my developments and I had no problem.
I hope this solves your doubt. I will do my best to get the original links and leave the instructions in the README file.

(Sorry for my English, I speak Spanish)

**Comment by Snorvarg** [comment]
Hi edgardo! Thanks a lot for uploading these. 

The original project with the source code can be found here:
https://github.com/RonaldCarter/PHPManager

..However, I don't know if the .msi-files are easily available there.

**Comment by lextm** [comment]
@Snorvarg I don't believe the repo you pointed out is "the original". That repo also has its own issues (for example, upgrading to .NET Framework 4.x will break Windows Vista/7/Server 2008/R2).

The official repo is still on CodePlex, and nobody truly takes it over, so it is still a dead one,

https://archive.codeplex.com/?p=phpmanager

**Comment by Snorvarg** [comment]
You are absolutely right lextm, thanks for correcting! I had that link to CodePlex in mind when I wrote, but changed the link to one of the most popular repositories at Github where they have 'taken it over'. The reason I changed is that I try to avoid spreading 'dead' links.

**Comment by edgardo001** [comment]
In fact, many of the links are dead or without updates, it is strange that the project is dead, I think it is useful to increase the php servers quickly. For these reasons, I created this repository with installers .msi for each version of Windows. In the "original" repository the project must be compiled and that does not guarantee that it works or that all the dependencies are configured correctly, you should think of developers who are just learning and who only want to develop in php and not have to install all the IDE of VisualStudio to compile the php installer, if that were the case, it would be easier to install php in a normal way in IIS or from WebInstaler.

I hope this does not cause problems to my account, I just want to facilitate the distribution of this project for interested developers and that it has cost them to find the corresponding installers for each version of Windows.

I do not intend to earn credit with this project, since it really does not belong to me and it would be perfect for the developer to continue updating this project.

**Comment by edgardo001** [comment]
I edit the above, so I see the project is still open, when I created this repository it cost me enough to find these installers, and that was the decision to publish them.

**Comment by lextm** [comment]
My suggestion is that someone steps in and fully take over the project,

* Learn its code base (primarily in C#).
* Configure a CI system to build it (AppVeyor I assume).
* Maintain its installers.

I can provide some assistance, but I don't really know PHP.

Anyone interested in?

**Comment by lextm** [comment]
I decided to build an organization to fully take over the original project,

https://github.com/phpmanager/phpmanager/issues/1

Join me if you like.

**Comment by lextm** [comment]
While digging further into the CodePlex archive, I think I found the source of your installers,
```
PHP Manager for IIS8 IIS8.5 IIS10
Hello, I compiled specifically new installers for IIS8-8.5 IIS10 
![Image](http://s020.radikal.ru/i714/1510/23/a79c72eb12be.jpg)
![Image](http://s020.radikal.ru/i706/1510/61/01734c79ebc2.jpg)
![Image](http://s020.radikal.ru/i713/1510/e9/2abf31024b58.jpg)
![Image](http://s013.radikal.ru/i323/1510/f9/b68b51b9b0bd.jpg)

[PHP Manager 1.4 for IIS 10](https://onedrive.live.com/redir?resid=47DF1DC3942D52B3!2357&authkey=!APYPwnsyjJm4zDw&ithint=file%2cmsi)
[PHP Manager 1.3 for IIS 8-8.5](https://onedrive.live.com/redir?resid=47DF1DC3942D52B3!2356&authkey=!AM3GEwo4u7cUqcI&ithint=file%2cmsi)

Thanks for the support:
PayPal:xxxvcojocarixxx@gmail.com
WMZ:Z162199218738
WMR:R250322323111
WME:E241475837014
32bit version added
https://phpmanager.codeplex.com/workitem/2653
please test and reply
THX
2016-01-09
Not need to recompile, just change temporally reg at

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W3SVC\Parameters
+ MajorVersion = 9

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\InetStp
+ MajorVersion = 9
2016-01-23
Proposed
#2734 | Created 2015-10-03 | Updated 2016-01-23
```

However, not sure how that guy created the installers.

**Comment by Snorvarg** [comment]
lextm, don't forget to check out the other repos, like the one I mentioned above. https://github.com/RonaldCarter/PHPManager

..I guess they have done some job, so don't miss it out!

**Comment by lextm** [comment]
@Snorvarg I checked all similar repos, but none of them seems to move the project forward.
